language: java
jdk: openjdk11

before_install:
  # Checkout master branch not commit on master builds
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git checkout $TRAVIS_BRANCH;
    fi
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn fmt:check
  - curl ifconfig.co|xargs echo "Travis IP address is ";


script:
  - mvn test -B
  # Only release on master builds
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git config --global user.email "travis@travis-ci.org";
    git config --global user.name "Travis CI";
    mvn -B -Dusername=$GITHUB_API_KEY release:prepare;
    mvn -B release:perform;
    fi

notifications:
  #slack:
  #   rooms:
  #    secure: Gf9XUUEittFhVvvu4YPx2wLBSyvMReogWDz0zus0585ETpf/ar6gHJ5KUcDtkDHoDBQpGmltoDmfVpQLMlBGFP8qwU1p/B01JQiTT2TxY99stECIKc+guuaM2lrXC1KIcaNAGJmdmGoTv0YgVlzbCJcSUstKpPm9ZseT8zILoQ4B2ZG3F8kHtZRHS2eAmSp0YIuU0kN4sEzWhZDmcJjsBIFPwlOovoMNgMiTFFhEA5VNHiDvYDcITpKHrB4uladbwaQoO/CF+kDkz+0ho/3t+emObQT3NHa9FuzkrcoKoj0lsDopfpOgDabVyh73ivAIh9STVpWDCpUSJdkfhAjoPU3Fh5pIvkKxLiCfBMNBIGIkNdn9kSIrA1ajpyHI0+QqIey0CNzP1JkQyIqrMCjrEiKYCc7eZEve94GK1piumciDBXXiZRsHW9yaiDATlh0Jf5fwTKa5UE3uHyjN2xd6468gRp897ai+eN80QKUHFU5WGPAV40WHhdM3jR3ACCPTWeJchT9OJD9yJ7Zot/adcZjNuYqu4wrZMzsMh+Ufqmyqa5nVClRiCFex/+4o55/bedMZmOy1y9vvvG6bU6aeh9JEseC8QSCeVcbNaPXXnPmvfXew4u6YknTGj4KLowdPlPdh0ivSZ7QcycEuqxzYf3qVqk4zn2uHB7onAcIeeS0=
  #  on_failure: always
  #  on_success: never

cache:
  directories:
  - $HOME/.m2

branches:
    only:
        - master
